'use client'

import { useRouter } from 'next/navigation'
import PageShell from '@/app/components/PageShell'
import { useMockApp } from '@/app/providers'

export default function ProfilePage() {
  const router = useRouter()
  const { user, updateProfile, signOut } = useMockApp()
  if (!user) return <PageShell><main className="container-primary min-h-screen py-12"><div className="card"><h1 className="text-2xl font-bold text-gray-900">Profile unavailable</h1><p className="mt-2 text-gray-600">Sign in to use the mock profile.</p><button className="btn-primary mt-5" onClick={() => router.push('/auth/login')}>Sign in</button></div></main></PageShell>
  return <PageShell><main className="min-h-screen bg-gray-50"><section className="container-primary py-8 md:py-12"><form className="card max-w-3xl" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); updateProfile({ ...user, name: String(form.get('name')), email: String(form.get('email')), phone: String(form.get('phone')), neighborhood: String(form.get('neighborhood')), bio: String(form.get('bio')), interests: String(form.get('interests')).split(',').map((item) => item.trim()).filter(Boolean) }) }}><p className="pill mb-4">Mock profile</p><h1 className="text-3xl font-bold text-gray-900">Your profile</h1><p className="mt-2 text-gray-600">Editable local profile used by create, post, and message flows.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="grid gap-2"><span className="field-label">Name</span><input name="name" defaultValue={user.name} className="field-input" /></label><label className="grid gap-2"><span className="field-label">Email</span><input name="email" type="email" defaultValue={user.email} className="field-input" /></label><label className="grid gap-2"><span className="field-label">Phone</span><input name="phone" defaultValue={user.phone} className="field-input" /></label><label className="grid gap-2"><span className="field-label">Neighborhood</span><input name="neighborhood" defaultValue={user.neighborhood} className="field-input" /></label></div><label className="mt-4 grid gap-2"><span className="field-label">Bio</span><textarea name="bio" defaultValue={user.bio} rows={4} className="field-input" /></label><label className="mt-4 grid gap-2"><span className="field-label">Interests</span><input name="interests" defaultValue={user.interests.join(', ')} className="field-input" /></label><div className="mt-6 flex flex-col gap-3 sm:flex-row"><button className="btn-primary" type="submit">Save profile</button><button type="button" className="btn-secondary" onClick={() => { signOut(); router.push('/') }}>Sign out</button></div></form></section></main></PageShell>
}
